#!/bin/sh /etc/rc.common

# MAC addresses of connected clients are stored in a sqlite database.
# Having the database seems to be necessary for the device to be working properly.
# We intent to have the device store the database in RAM rather than on flash.
# We replace the directory with a memory-backed tmpfs which is as volatile as we can make it.

# We want to run ahead of "gl-tertf" which, currently, has a prioprity of 60.
# We also want to run ahead of "gl_clients" which has 99.
START=59
STOP=99

start() {
	/lib/blue-merle/mac-wipe.sh
}

stop() {
	shred /etc/oui-tertf/client.db ||  rm -f /etc/oui-tertf/client.db
}

